# Generated by Django 5.1.6 on 2025-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="max_participants",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
