# Generated by Django 5.1.6 on 2025-03-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_meeting_max_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
